// <auto-generated />
using EnhanceRustPlus.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnhanceRustPlus.EfCore.Migrations
{
    [DbContext(typeof(EnhanceRustPlusDbContext))]
    [Migration("20240528154932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Category", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Channel", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChannelType");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.ChannelType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ChannelTypes");

                    b.HasData(
                        new
                        {
                            Name = "INFORMATION"
                        },
                        new
                        {
                            Name = "SERVERS"
                        },
                        new
                        {
                            Name = "SETTINGS"
                        },
                        new
                        {
                            Name = "COMMANDS"
                        },
                        new
                        {
                            Name = "EVENTS"
                        },
                        new
                        {
                            Name = "TEAM_CHAT"
                        },
                        new
                        {
                            Name = "SWITCHES"
                        },
                        new
                        {
                            Name = "ALARMS"
                        },
                        new
                        {
                            Name = "ACTIVITY"
                        });
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Message", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("MessageType");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.MessageType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            Name = "INFO_MAP"
                        },
                        new
                        {
                            Name = "INFO_INFORMATION"
                        },
                        new
                        {
                            Name = "INFO_EVENT"
                        },
                        new
                        {
                            Name = "INFO_TEAM"
                        },
                        new
                        {
                            Name = "SETTINGS_TITLE"
                        });
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Role", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Category", b =>
                {
                    b.HasOne("EnhanceRustPlus.EfCore.Entities.Guild", "Guild")
                        .WithOne("Category")
                        .HasForeignKey("EnhanceRustPlus.EfCore.Entities.Category", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Channel", b =>
                {
                    b.HasOne("EnhanceRustPlus.EfCore.Entities.Category", "Category")
                        .WithMany("Channels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhanceRustPlus.EfCore.Entities.ChannelType", null)
                        .WithMany("Channels")
                        .HasForeignKey("ChannelType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Message", b =>
                {
                    b.HasOne("EnhanceRustPlus.EfCore.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhanceRustPlus.EfCore.Entities.MessageType", null)
                        .WithMany("Messages")
                        .HasForeignKey("MessageType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Role", b =>
                {
                    b.HasOne("EnhanceRustPlus.EfCore.Entities.Guild", "Guild")
                        .WithOne("Role")
                        .HasForeignKey("EnhanceRustPlus.EfCore.Entities.Role", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Category", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.ChannelType", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.Guild", b =>
                {
                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("EnhanceRustPlus.EfCore.Entities.MessageType", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
